name: frontend workflow
on:
    push:
        paths-ignore:
            - '.github/workflows/**'
        branches: 
            - main
    workflow_dispatch:
jobs:
    angular:
        runs-on: ubuntu-latest

        steps:
            - name: print somethings
              run: echo "deploying angular"