name: Terraform workflow

on:
    push:
        branches:
            - aws-infra-servers
    pull_request:
        branches:
            - aws-infra-servers

jobs:
    terraform:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with: 
                terraform_version: "1.6.4"
            
            - name: Terraform Init
              run: terraform init

            - name: Terraform Validate
              run: terraform validate

            - name: Terraform plan
              run: terraform plan

            - name: Terraform Apply
              if: github.event_name == 'push' && github.ref == 'refs/heads/aws-infra-servers'
              run: terraform apply -auto-approve

            - name: Terraform Show
              run: terraform show